export const Colors = {
  black: '#000000',
  black100: '#1E1E1E',
  black200: '#3E3E3E',
  white: '#FFFFFF',
  white100: '#D9D9D9',
  white200: '#F0F0F0',
  blue: '#2962FF',
  green: '#00E676',
  background: '#2F2F2F',
  primary: '#B388FF',
};

export const DarkTheme = {
  dark: true,
  colors: {
    dateHeader: Colors.white,
    activeDate: Colors.white,
    activeDateLabel: Colors.black,
    dateLabel: Colors.white,
    background: Colors.background,
    primary: Colors.primary,
    secondary: Colors.white100,
    prioPill: Colors.white100,
    nonPrioPill: Colors.black100,
    nonPrioPillLabel: Colors.white,
    nonPrioCard: Colors.black200,
    nonPrioLabel: Colors.white,
    tickBackground: Colors.white100,
    buttonBorder: Colors.white,
    buttonBorderText: Colors.white,
    submitBackground: Colors.green,
    submitLabel: Colors.black,
    modalNav: Colors.blue,
    icon: Colors.white,
    addIcon: Colors.black,
    addBg: Colors.white200,
  },
};
